# Generated by Django 4.2 on 2023-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='preco',
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='itens_alugados',
            field=models.ManyToManyField(blank=True, to='agenda.item'),
        ),
    ]
